# Generated by Django 5.2.4 on 2025-12-30 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sick_leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleavesmodel',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issued_sick_leaves', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
