# Generated by Django 5.2.4 on 2025-10-04 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_doctor',
            },
        ),
    ]
