# Generated by Django 5.2.4 on 2025-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesmodels',
            name='is_available_for_booking',
            field=models.BooleanField(default=True),
        ),
    ]
