# Generated by Django 5.2.4 on 2025-07-31 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profilemodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(?:\\+46|0046|0)7\\d{8}$', 'Enter a valid Swedish mobile number. Allowed formats: +46701234567, 0046701234567, or 0701234567.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='region',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29})([ -][A-Z][a-z]{0,29})*$', 'Only alpha characters are allowed.')]),
        ),
    ]
