# Generated by Django 5.2.4 on 2025-07-31 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profilemodel_age_alter_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='house',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[\\dA-Za-z\\s\\-\\/]*$', 'House number may contain letters, digits, spaces, dashes, or slashes.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][a-z]{0,29}\\.?)([ -][A-Z][a-z]{0,29}\\.?)*$', 'Only alpha characters are allowed.')]),
        ),
    ]
