# Generated by Django 5.2.4 on 2025-12-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profilemodel_house_alter_profilemodel_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(?:\\+46|0046|0)7\\d{8}$', 'Enter a valid Swedish mobile number. Allowed formats: +46701234567, +46700000000, or 0701234567.')]),
        ),
    ]
