# Generated by Django 5.2.4 on 2025-10-09 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDiagnosticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diagnostic_by', to=settings.AUTH_USER_MODEL)),
                ('diagnostic_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diagnostic_user', to='diagnostics.diagnosticsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diagnostic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_diagnostic',
            },
        ),
    ]
