# Generated by Django 5.2.4 on 2025-10-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_diagnostic', '0001_initial'),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdiagnosticmodel',
            name='diagnostic_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_diagnostic_user', to='diagnostics.diagnosticsmodel'),
        ),
    ]
