# Generated by Django 5.2.4 on 2025-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_diagnostic', '0002_alter_bookingdiagnosticmodel_diagnostic_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdiagnosticmodel',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
