from .send_birthday_email_task import happy_birthday
from .send_create_role_email_task import send_create_role_email_task
from .send_happy_new_year_email_task import happy_new_year
from .send_merry_christmas_email_task import merry_christmas_email
from .send_patient_booking_diagnostic_by_staff import send_patient_booking_diagnostic_by_staff
from .send_patient_booking_diagnostic_email_task import send_patient_booking_diagnostic_email_task
from .send_patient_message_email_task import send_patient_message_email_task
from .send_welcome_to_qhealt_email_task import send_welcome_to_qhealt_email
